<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Spring Cloud' Course: Resilient Inter-Service Communication</description>
    <name>resilient-inter-service-communication</name>

    <groupId>com.baeldung</groupId>
    <artifactId>lsc-resilient-inter-service-communication</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>resilient-communication-start</module>
        <module>resilient-communication-end</module>
        <module>circuit-breaker-start</module>
        <module>circuit-breaker-end</module>
        <module>feign-cb-start</module>
        <module>feign-cb-end</module>
        <module>fallbacks-start</module>
        <module>fallbacks-end</module>
    </modules>
</project>
