<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Spring Cloud' Course: Centralized Configuration Management</description>
    <name>centralized-configuration-management</name>

    <groupId>com.baeldung</groupId>
    <artifactId>lsc-centralized-configuration-management</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>config-server-start</module>
        <module>config-server-end</module>
        <module>config-server-clients-start</module>
        <module>config-server-clients-end</module>
    </modules>
</project>
