server.port=8080
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.cloud.openfeign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.configs.default.slidingWindowSize=5
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.configs.default.recordExceptions=feign.RetryableException
resilience4j.circuitbreaker.configs.default.ignoreExceptions=feign.FeignException.BadRequest
