spring.application.name=task-service
server.port=8080

spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.instance-id=${spring.application.name}:${random.value}
