server.port=8080
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

notification-service.url=http://localhost:8081

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.enabled=false
