server.port=8080
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

resilience4j.circuitbreaker.instances.campaign-cb.slidingWindowSize=5
resilience4j.circuitbreaker.instances.campaign-cb.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.campaign-cb.failureRateThreshold=50
resilience4j.circuitbreaker.instances.campaign-cb.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.campaign-cb.permittedNumberOfCallsInHalfOpenState=2